config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/saml/auth' => 'saml_idp#new'
  get '/saml/metadata' => 'saml_idp#show'
  post '/saml/auth' => 'saml_idp#create'
  match '/saml/logout' => 'saml_idp#logout', via: [:get, :post, :delete]
end

app/models/user.rb
User = Struct.new(:email) do
  def persistent
    email
  end

  def email_address
    email
  end

    def asserted_attributes
      {

        email: {
          getter: :email,
          name_format: Saml::XML::Namespaces::Formats::NameId::EMAIL_ADDRESS,
          name_id_format: Saml::XML::Namespaces::Formats::NameId::EMAIL_ADDRESS
        }
      }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/saml_idp_controller.rb
class SamlIdpController < SamlIdp::IdpController
  layout "application"

  def idp_authenticate(email, password)
    User.new(email)
  end

  def idp_make_saml_response(user)
    encode_response user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div>
  <h1>Evil SSO</h1>
  Metadata: <a href="<%= saml_metadata_url %>"><%= saml_metadata_url %></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaiveIdp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <style>
    * {
      background-color: black;
      color: red;
    }
  </style>

  <body>
    <%= yield %>
  </body>
</html>

app/views/saml_idp/idp/new.html.erb
<div style="width: 100%; text-align: center;">
  <img src="/evil.png">
  <% if @saml_idp_fail_msg %>
    <div id="saml_idp_fail_msg" class="flash error"><%= @saml_idp_fail_msg %></div>
  <% end %>

  <%= form_tag do %>
    <%= hidden_field_tag("SAMLRequest", params[:SAMLRequest]) %>
    <%= hidden_field_tag("RelayState", params[:RelayState]) %>

    <p>
      <%= label_tag :email %>
      <%= email_field_tag :email, params[:email], :autocapitalize => "off", :autocorrect => "off", :autofocus => "autofocus", :spellcheck => "false", :size => 30, :class => "email_pwd txt" %>
      <%= submit_tag "Sign in", :class => "button big blueish" %>
    </p>
  <% end %>
</div>